/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controladores.ConectarBD;
import Modelos.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gerardo
 */
public class Home extends javax.swing.JFrame {
    
    private List<String> productosAgregados = new ArrayList<String>();
    private String modelo;
    private final String nombreColumnas[] = {"Nombre","Modelo","Numero de parte","Precio"};
    private Producto producto;
    DefaultTableModel model = new DefaultTableModel(null, nombreColumnas);
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerra = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonVentas = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jButtonAlmacen = new javax.swing.JButton();
        jLabelFondoMenu = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonVender = new javax.swing.JButton();
        jLabelNameUsuario = new javax.swing.JLabel();
        jLabelDescripcionProd = new javax.swing.JLabel();
        jLabelNombreProd = new javax.swing.JLabel();
        jLabelIdProducto = new javax.swing.JLabel();
        jLabelCantidadProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCerra.setText("X");
        jButtonCerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerraActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, -1));

        jButtonCerrarSesion.setText("Cerrar Sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        jButtonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Imagenes/iconCarShop.png"))); // NOI18N
        jButtonVentas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Imagenes/iconCarShopSelec.png"))); // NOI18N
        getContentPane().add(jButtonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, -1, -1));

        jButtonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Imagenes/iconUsers.png"))); // NOI18N
        jButtonUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Imagenes/iconUsersSelec.png"))); // NOI18N
        getContentPane().add(jButtonUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 130, -1, -1));

        jLabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Imagenes/iconUser.png"))); // NOI18N
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 60, 60));

        jButtonAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Imagenes/iconStock.png"))); // NOI18N
        jButtonAlmacen.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Imagenes/iconStockSelec.png"))); // NOI18N
        getContentPane().add(jButtonAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 230, -1, -1));

        jLabelFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Imagenes/Fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 100, 690));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 250, 30));
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, 30));
        getContentPane().add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 250, 30));

        jLabelDescripcion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 240, 90));

        jButtonBuscar.setText("Buscar por #Parte");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        jButtonCancelar.setText("Cancelar");
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        jButtonVender.setText("Vender");
        getContentPane().add(jButtonVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, -1, -1));

        jLabelNameUsuario.setText("Bienvenid@ name");
        getContentPane().add(jLabelNameUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, -1, -1));

        jLabelDescripcionProd.setText("Descripcion");
        getContentPane().add(jLabelDescripcionProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabelNombreProd.setText("Nombre del producto");
        getContentPane().add(jLabelNombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabelIdProducto.setText("Numero de parte");
        getContentPane().add(jLabelIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabelCantidadProducto.setText("Cantidad disponible");
        getContentPane().add(jLabelCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, 370));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerraActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCerraActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login frameInicio = new Login();
        frameInicio.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:}
        ConectarBD conexion = new ConectarBD();
        producto = conexion.buscarProducto(jTextFieldId.getText());
        if(producto!=null){
            if(producto.getCantidad()<1)
                JOptionPane.showMessageDialog(null, "El producto no esta disponible.");
            else{
                jTextFieldNombre.setText(producto.getNombreProducto());
                jTextFieldCantidad.setText(producto.getCantidad()+"");
                jLabelDescripcion.setText(producto.getDescripcion());
                modelo = producto.getModelo();
            }
        }else{
            JOptionPane.showMessageDialog(null, "El producto no esta disponible.");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        if(jTextFieldNombre.getText().equals("")||jTextFieldCantidad.getText().equals("") || jTextFieldCantidad.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No ha seleccionado el articulo.");
        }
        else{
            if(productosAgregados.size()<1)
            productosAgregados.add(jTextFieldId.getText());
            agregarProductoTabla(producto);
            jTextFieldNombre.setText("");
            jTextFieldId.setText("");
            jTextFieldCantidad.setText("");
            jLabelDescripcion.setText("Se agrego correctamente");
        }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed
    public void agregarProductoTabla(Producto produc){
        Object[] dato = new Object[nombreColumnas.length];
        dato[0] = produc.getNombreProducto();
        dato[1] = produc.getModelo();
        dato[2] = produc.getNumeroParte();
        dato[3] = produc.getPrecio();
        model.addRow(dato);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAlmacen;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCerra;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JButton jButtonVentas;
    private javax.swing.JLabel jLabelCantidadProducto;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDescripcionProd;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoMenu;
    private javax.swing.JLabel jLabelIdProducto;
    private javax.swing.JLabel jLabelNameUsuario;
    private javax.swing.JLabel jLabelNombreProd;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
